# Generated by Django 4.0.3 on 2022-04-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_rename_vehicles_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('R & D', 'run & drive'), ('S', 'start'), ('N/W', 'not working')], max_length=10)),
                ('seller', models.CharField(max_length=10)),
                ('primary_damage', models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10)),
                ('secondary_damage', models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10)),
                ('retail_value', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('make', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('status', models.CharField(choices=[('R & D', 'run & drive'), ('S', 'start'), ('N/W', 'not working')], max_length=10)),
                ('seller', models.CharField(max_length=10)),
                ('primary_damage', models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10)),
                ('secondary_damage', models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10)),
                ('retail_value', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='primary_damage',
            field=models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='secondary_damage',
            field=models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10),
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('make', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('R & D', 'run & drive'), ('S', 'start'), ('N/W', 'not working')], max_length=10)),
                ('seller', models.CharField(max_length=10)),
                ('primary_damage', models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10)),
                ('secondary_damage', models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10)),
                ('retail_value', models.CharField(max_length=10)),
                ('body_style', models.CharField(choices=[('Van Trailer', 'Van Trailer'), ('Dump Trailer', 'Dump Trailer'), ('Livestock Trailer', 'Livestock Trailer'), ('Logging Trailer', 'Logging Trailer'), ('Travel Trailer', 'Travel Trailer'), ('Utility Trailer', 'Utility Trailer'), ('Tank Trailer', 'Tank Trailer')], max_length=17)),
                ('color', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(max_length=10)),
                ('vin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auction.vin')),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('make', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('R & D', 'run & drive'), ('S', 'start'), ('N/W', 'not working')], max_length=10)),
                ('seller', models.CharField(max_length=10)),
                ('primary_damage', models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10)),
                ('secondary_damage', models.CharField(choices=[('AO', 'All Over - AO'), ('BC', 'Biohazard/Chemical - BC'), ('BN', 'Burn - BN'), ('BE', 'Burn - Engine - BE'), ('BI', 'Burn - Interior - BI'), ('CC', 'Cash for Clunkers - CC'), ('DH', 'Damage History - DH'), ('FD', 'Frame Damage Reported - FD'), ('FR', 'Front End - FR'), ('HL', 'Hail - HL'), ('MC', 'Mechanical - MC'), ('MW', 'Minor Dents/Scratches - MN'), ('NW', 'Normal Wear - NW'), ('PR', 'Partial/Incomplete Repair - PR'), ('RJ', 'Rejected Repair - RJ'), ('RO', 'Rollover - RO'), ('RR', 'Rear end - RR'), ('SD', 'Side Damage - SD'), ('ST', 'Stripped - ST'), ('TP', 'Top/Roof Damage - TP'), ('UK', 'Unknown - UK'), ('UN', 'Undercarriage - UN'), ('VN', 'Vandalism - VN'), ('VI', 'VIN - Missing/Altered - VI'), ('VP', 'VIN - Replaced - VP'), ('WA', 'Water/Flood - WA')], max_length=10)),
                ('retail_value', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(choices=[('Standard', 'Standard'), ('Cruiser', 'Cruiser'), ('Sport Bike', 'Sport Bike'), ('Touring', 'Touring'), ('Sport Touring', 'Sport Touring'), ('Dual Sport', 'Dual Sport'), ('Scooter', 'Scooter'), ('Moped', 'Moped'), ('Off-road', 'Off-road')], max_length=13)),
                ('color', models.CharField(max_length=10)),
                ('engine_type', models.CharField(choices=[('Single', 'Single'), ('Inline', 'Inline'), ('V', 'V'), ('L-Twin', 'L-Twin'), ('Flat', 'Flat')], max_length=10)),
                ('engine_cycle', models.CharField(choices=[('2T', '2T'), ('4T', '4T')], max_length=10)),
                ('cylinders', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('cooling', models.CharField(choices=[('Air Cooling', 'Air Cooling'), ('Liquid Cooling', 'Liquid Cooling')], max_length=14)),
                ('transmission_type', models.CharField(choices=[('Sequential', 'Sequential'), ('CVT', 'CVT'), ('Dual Clutch', 'Dual Clutch'), ('Centrifugal Clutch', 'Centrifugal Clutch')], max_length=18)),
                ('notes', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(max_length=10)),
                ('vin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auction.vin')),
            ],
        ),
    ]
