# Generated by Django 4.0.3 on 2022-04-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_otheritem_sparepart_alter_vehicle_primary_damage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('White', 'White'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('Silver', 'Silver'), ('Brown', 'Brown'), ('Grey', 'Grey'), ('Pink', 'Pink'), ('Olive', 'Olive'), ('Maroon', 'Maroon'), ('Violet', 'Violet'), ('Charcoal', 'Charcoal'), ('Magenta', 'Magenta'), ('Bronze', 'Bronze'), ('Cream', 'Cream'), ('Gold', 'Gold'), ('Tan', 'Tan'), ('Teal', 'Teal'), ('Mustard', 'Mustard'), ('Navy Blue', 'Navy Blue'), ('Coral', 'Coral'), ('Burgundy', 'Burgundy'), ('Lavender', 'Lavender'), ('Mauve', 'Mauve'), ('Peach', 'Peach'), ('Rust', 'Rust'), ('Indigo', 'Indigo'), ('Ruby', 'Ruby'), ('Clay', 'Clay'), ('Cyan', 'Cyan'), ('Azure', 'Azure'), ('Beige', 'Beige'), ('Off White', 'Beige'), ('Turquoise', 'Turquoise'), ('Amber', 'Amber'), ('Mint', 'Mint')], max_length=9),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/auction'),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='notes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='retail_value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='seller',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('White', 'White'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('Silver', 'Silver'), ('Brown', 'Brown'), ('Grey', 'Grey'), ('Pink', 'Pink'), ('Olive', 'Olive'), ('Maroon', 'Maroon'), ('Violet', 'Violet'), ('Charcoal', 'Charcoal'), ('Magenta', 'Magenta'), ('Bronze', 'Bronze'), ('Cream', 'Cream'), ('Gold', 'Gold'), ('Tan', 'Tan'), ('Teal', 'Teal'), ('Mustard', 'Mustard'), ('Navy Blue', 'Navy Blue'), ('Coral', 'Coral'), ('Burgundy', 'Burgundy'), ('Lavender', 'Lavender'), ('Mauve', 'Mauve'), ('Peach', 'Peach'), ('Rust', 'Rust'), ('Indigo', 'Indigo'), ('Ruby', 'Ruby'), ('Clay', 'Clay'), ('Cyan', 'Cyan'), ('Azure', 'Azure'), ('Beige', 'Beige'), ('Off White', 'Beige'), ('Turquoise', 'Turquoise'), ('Amber', 'Amber'), ('Mint', 'Mint')], max_length=9),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('White', 'White'), ('Black', 'Black'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('Silver', 'Silver'), ('Brown', 'Brown'), ('Grey', 'Grey'), ('Pink', 'Pink'), ('Olive', 'Olive'), ('Maroon', 'Maroon'), ('Violet', 'Violet'), ('Charcoal', 'Charcoal'), ('Magenta', 'Magenta'), ('Bronze', 'Bronze'), ('Cream', 'Cream'), ('Gold', 'Gold'), ('Tan', 'Tan'), ('Teal', 'Teal'), ('Mustard', 'Mustard'), ('Navy Blue', 'Navy Blue'), ('Coral', 'Coral'), ('Burgundy', 'Burgundy'), ('Lavender', 'Lavender'), ('Mauve', 'Mauve'), ('Peach', 'Peach'), ('Rust', 'Rust'), ('Indigo', 'Indigo'), ('Ruby', 'Ruby'), ('Clay', 'Clay'), ('Cyan', 'Cyan'), ('Azure', 'Azure'), ('Beige', 'Beige'), ('Off White', 'Beige'), ('Turquoise', 'Turquoise'), ('Amber', 'Amber'), ('Mint', 'Mint')], max_length=9),
        ),
    ]
