# Generated by Django 4.0.3 on 2022-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_vin_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='vin',
            field=models.CharField(default='WDB2110281A301836', max_length=17),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='vin',
            field=models.CharField(default='WDB2110281A301836', max_length=17),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default='WDB2110281A301836', max_length=17),
        ),
        migrations.DeleteModel(
            name='Vin',
        ),
    ]
